name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby with .ruby-version file
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Test with Rake
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 4ede50495e464568418f343df292cc6af18111e7c44319c66938d6fbb2b6c837
      with:
        coverageCommand: bundle exec rake
